import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 500px;
    height: 500px;
    title: @tr("Rubbish Calculator"); 
    in-out property <int> counter: 42;
    in-out property <float> cur_val: 0;
    in-out property <float> mod_val: 0;
    callback request-increase-value();
    GridLayout {
        Text {
            text: "Counter: \{root.counter}";
        }

        Row {
            Text {
                font-size: 50px;
                text: "Current Value: ";
            }
            Text {
                text: "\{root.cur_val}";
            }
        
        }

        Text {
            text: "Modifing value";

        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
